### ISSUE TITLE
Error in Examplecode

### ISSUE THREAD

**Issue by NoxelS** [sancaruso/pdf-generator#2]
## Error in Examplecode
If I run the pdf-generator example (from npmjs.com) I get an error:
### Code:

```
var pdfGenerator = require("template-pdf-generator");
var fs = require("fs");
var data = {  name: "World"};
var template = "<h1>Hello {{name}}</h1>"; 
var css = "h1 {color: red}";
pdfGenerator(data, template, css).pipe(fs.createWriteStream("out.pdf"));
```

### Error:
```
Error: write EPIPE
    at _errnoException (util.js:992:11)
    at Socket._writeGeneric (net.js:764:25)
    at Socket._write (net.js:783:8)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at Socket.Writable.write (_stream_writable.js:290:11)
    at Socket.write (net.js:707:40)
    at Socket.Writable.end (_stream_writable.js:563:10)
    at Socket.end (net.js:499:31)
```

#### Any ideas how to fix it?

**Comment by Chococoin** [comment]
Same problem here!

**Comment by itafraji** [comment]
same issue

**Comment by krushndayshmookh** [comment]
anyone solved this?

**Comment by krushndayshmookh** [comment]
It can be solved using https://github.com/devongovett/node-wkhtmltopdf/issues/112#issuecomment-473035282
